spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  web:
    error:
      include-stacktrace: always

app:
  jwt:
    secret: "dev-jwt-secret-please-replace-with-something-long-and-random-1234567890"
