spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/echo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false"
    username: echo
    password: echo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

app:
  jwt:
    secret: "local-jwt-secret-please-replace-with-something-long-and-random-1234567890"
