-- Out-of-band schema change for environments with existing `users` rows.
-- Not a Flyway script: this project has no migration runner wired yet, and
-- the rest of the schema is generated by Hibernate ddl-auto. Applying this
-- as a Flyway V1 would be wrong because the `users` table itself has no
-- baseline migration; a future Flyway adoption must start with a full
-- baseline that captures the entire current schema.
--
-- Until Flyway is adopted, an operator should run this ALTER manually
-- against any populated `users` table before deploying the build that
-- introduces User.createdAt. On a greenfield deploy with ddl-auto=create
-- or ddl-auto=update against an empty schema, Hibernate emits the column
-- itself from the entity (see User.createdAt columnDefinition).

ALTER TABLE users
    ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
